name: sigfrotas
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  lib_observer:
    git:
      url: https://github.com/bicasoftware/lib_observer

  flutter_svg: ^0.17.4
  line_awesome_icons: ^1.0.4+2
  get:
  rxdart:
  sqflite:
  path_provider: ^1.4.0
  dio: ^3.0.9
  retrofit: ^1.3.4
  intl: ^0.15.8
  flutter_secure_storage:
  auto_size_text:
  http: ^0.12.1
  async: ^2.4.1
  material_design_icons_flutter: 4.0.5345
  validation_extensions: ^1.0.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  retrofit_generator:
  json_serializable: ^3.2.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
